before_install:
  - npm install -g npm@latest
  # Setup Grafana Repo
  - cd /home/travis/build
  - git clone https://github.com/grafana/grafana.git
  - cd grafana && git reset --hard d09749eaaa340a3b5601f46e693b7246d1313edb
  # Move plugin into grafana's public folder
  - cp -r /home/travis/build/$TRAVIS_REPO_SLUG /home/travis/build/grafana/public/app/plugins
script:
  - ./node_modules/karma/bin/karma start --single-run
  - cd /home/travis/build/$TRAVIS_REPO_SLUG
  - npm install
  - npm run test
language: node_js
node_js:
  - 10.3.0


